### ISSUE TITLE
Feature request: Allow setting of custom error tracking handler

### ISSUE THREAD

**Issue by the-overengineer** [joernroeder/piwik-react-router#44]
Hi,

At [oradian](https://github.com/oradian) we found ourselves in need of using some custom error handling/transformation logic, which we couldn't do with the default error tracking handler. Therefore, we added and documented an init option to set your own custom handler, which is then invoked in places where the old, default, handler would be invoked.

If you think you can make use of this in your project, see PR #43 for details.

**Comment by joernroeder** [comment]
thanks @the-overengineer! i've just pushed version 0.10.0 to npm 👍
